name: build and package
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_call:
jobs:
    build-and-package:
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      target: win32-x64
                    - os: windows-latest
                      target: win32-ia32
                    - os: windows-latest
                      target: win32-arm64
                    - os: ubuntu-latest
                      target: linux-x64
                    - os: ubuntu-latest
                      target: linux-arm64
                    - os: ubuntu-latest
                      target: linux-armhf
                    - os: ubuntu-latest
                      target: alpine-x64
                    - os: ubuntu-latest
                      target: alpine-arm64
                    - os: macos-latest
                      target: darwin-x64
                    - os: macos-latest
                      target: darwin-arm64
                    - os: ubuntu-latest
                      target: web
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: npm install
            - run: npx antlr4ts -o "../src/_generated" "AntlrGlslLexer.g4"
              working-directory: ./syntaxes
            - run: npx antlr4ts -o "../src/_generated" -no-listener -visitor "AntlrGlslParser.g4"
              working-directory: ./syntaxes
            - run: npx vsce package --target ${{ matrix.target }}
            - uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.target }}
                  path: '*.vsix'
