name: build
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      command: package-win32-x64
                    - os: windows-latest
                      command: package-win32-ia32
                    - os: windows-latest
                      command: package-win32-arm64
                    - os: ubuntu-latest
                      command: package-linux-x64
                    - os: ubuntu-latest
                      command: package-linux-arm64
                    - os: ubuntu-latest
                      command: package-linux-armhf
                    - os: ubuntu-latest
                      command: package-alpine-x64
                    - os: ubuntu-latest
                      command: package-alpine-arm64
                    - os: macos-latest
                      command: package-darwin-x64
                    - os: macos-latest
                      command: package-darwin-arm64
                    - os: ubuntu-latest
                      command: package-web
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: npm install
            - run: npx antlr4ts -o "../src/_generated" "AntlrGlslLexer.g4"
              working-directory: ./syntaxes
            - run: npx antlr4ts -o "../src/_generated" -no-listener -visitor "AntlrGlslParser.g4"
              working-directory: ./syntaxes
            - run: npm run lint
            - run: npm run ${{ matrix.command }}
