name: publish
on:
    release:
        types:
            - published
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: npm install
            - run: npx antlr4ts -o "../src/_generated" "AntlrGlslLexer.g4"
              working-directory: ./syntaxes
            - run: npx antlr4ts -o "../src/_generated" -no-listener -visitor "AntlrGlslParser.g4"
              working-directory: ./syntaxes
            - run: npm run package-web
            - run: npm run package-win32-x64
            - run: npm run package-win32-ia32
            - run: npm run package-win32-arm64
            - run: npm run package-darwin-x64
            - run: npm run package-darwin-arm64
            - run: npm run package-linux-x64
            - run: npm run package-linux-arm64
            - run: npm run package-linux-armhf
            - run: npm run package-alpine-x64
            - run: npm run package-alpine-arm64
            - run: npx vsce publish --packagePath $(find . -type f -name "*.vsix" | paste -sd " ")
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
